<a href="https://colab.research.google.com/github/xinyanz-erin/Applied-Finance-Project/blob/Judy/EU_verification_Judy_Problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [132]:
S0 = np.array([100, 100, 100])
K = 110
T = 1
r = 0
cov = np.array([[0.0625,0,0],[0,0.0625,0],[0,0,0.0625]])
n_step = 500
n_path = 10000

# What will work

In [85]:
sigma = 0.25
def BC(S0, K, B, T, r, sigma, cov, n_step, n_path):
  payoff = np.zeros(n_path)
  dt = T/n_step
  for i in range(n_path):
    S = S0
    for j in range(n_step):
      #random = np.random.multivariate_normal(mean = np.array([0, 0, 0]), cov = cov)
      random = np.random.normal(0, 1, 3)  #感覺這裡不太對 這樣變成他們的variance 是1?
      S = S * np.exp((r - (1/2)*sigma**2) * dt + np.sqrt(dt) * random * sigma)
      S_avg = np.average(S)
    payoff[i] = max(np.average(S) - K, 0)
  price = np.exp(-r * T) * np.average(payoff)
  return price

In [86]:
BC(S0, K, B, T, r, sigma, cov, n_step, n_path)  #但生成出來接近2.多

2.1012066025046536

# Not Work?

In [134]:
def BC2(S0, K, B, T, r, sigma, cov, n_step, n_path):
  payoff = np.zeros(n_path)
  dt = T/n_step
  for i in range(n_path):
    S = S0
    random = np.random.multivariate_normal(mean = np.array([0, 0, 0]), cov = cov, size = (1, n_step))  #把random提上來一層
    #print(random)
    for j in range(n_step):
      random_step = random[0,j]
      #print(random_step)
      sigma = cov[0,0] ** 0.5
      S = S * np.exp((r - (1/2)*sigma**2) * dt + np.sqrt(dt) * random_step)
      S_avg = np.average(S)
    payoff[i] = max(np.average(S) - K, 0)
  price = np.exp(-r * T) * np.average(payoff)
  return price

In [126]:
cov = np.array([[0.0625,0,0],[0,0.0625,0],[0,0,0.0625]])

In [127]:
a = np.random.multivariate_normal(mean = np.array([0, 0, 0]), cov = cov, size = (1, n_step))
print(a)
#print(a[0,1])

[[[ 1.20653638e-01 -5.62258703e-01  7.39958348e-02]
  [ 2.35490993e-01  2.37623087e-01 -1.00236524e-01]
  [-2.08770037e-02  2.17930051e-01  1.04509202e-01]
  [ 3.38370637e-01  1.58558404e-02 -2.29244280e-01]
  [-3.72009804e-01 -1.63141043e-01 -2.86530482e-01]
  [-4.82511280e-01 -4.55535571e-01  6.31770257e-02]
  [ 2.59397526e-01 -2.08073678e-01  8.83355557e-02]
  [ 2.40274147e-01  2.09936387e-01  6.67505054e-02]
  [-7.40087512e-02 -1.40297629e-01  4.51975315e-01]
  [-4.25036140e-02  3.03087066e-01 -3.55249518e-01]
  [-2.41810587e-01  3.79061033e-01  4.65530968e-01]
  [-5.88527826e-01  6.52967568e-01 -1.16258869e-02]
  [-1.91838007e-01 -1.38483243e-02  1.56528643e-01]
  [ 4.64428394e-01  6.12282239e-02  2.19657767e-01]
  [ 3.02000572e-01 -6.52836245e-01  4.71563050e-01]
  [-3.16407325e-01  3.39681422e-01  1.99332303e-01]
  [-1.09188025e-01  2.64032717e-01  6.00475523e-02]
  [-3.53513104e-01 -7.64533531e-05 -2.31213889e-01]
  [ 5.76379485e-01 -1.16755895e-01  3.49078201e-01]
  [-1.327003

In [135]:
BC2(S0, K, B, T, r, sigma, cov, n_step, n_path)   #變成超級小????

2.3959545237114415

# Original

In [46]:
S0 = np.array([100, 100, 100])
K = 110
B = 80
T = 1
r = 0
sigma = 0.25
cov = np.identity(3)
n_step = 100
n_path = 5000

In [44]:
def BC(S0, K, B, T, r, sigma, cov, n_step, n_path):
  payoff = np.zeros(n_path)
  dt = T/n_step
  for i in range(n_path):
    S = S0
    for j in range(n_step):
      # random = np.random.multivariate_normal(mean = np.array([0, 0, 0]), cov = cov)
      random = np.random.normal(0, 1, 3)

      S = S * np.exp((r - (1/2)*sigma**2) * dt + np.sqrt(dt) * random * sigma)
      S_avg = np.average(S)
    payoff[i] = max(np.average(S) - K, 0)
    # payoff[i] = max(np.average(S)-K,0)
    # payoff[i] = max(S[0]-K, 0)

  price = np.exp(-r * T) * np.average(payoff)
  return price

In [47]:
BC(S0, K, B, T, r, sigma, cov, n_step, n_path)

2.2254919135919757