<a href="https://colab.research.google.com/github/xinyanz-erin/Applied-Finance-Project/blob/Lilian/European_jax_random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!curl https://colab.chainer.org/install |sh -
import cupy

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1580  100  1580    0     0   7596      0 --:--:-- --:--:-- --:--:--  7596
+ apt -y -q install cuda-libraries-dev-10-0
Reading package lists...
Building dependency tree...
Reading state information...
cuda-libraries-dev-10-0 is already the newest version (10.0.130-1).
0 upgraded, 0 newly installed, 0 to remove and 37 not upgraded.
+ pip install -q cupy-cuda100  chainer 
     |████████████████████████████████| 58.9 MB 19 kB/s 
     |████████████████████████████████| 1.0 MB 40.8 MB/s 
+ set +ex
Installation succeeded!


In [2]:
# Peter's code

def simple_process(key, initial_stocks, numsteps, drift, cov):
    stocks_init = jnp.zeros((numsteps + 1, initial_stocks.shape[0]))
    stocks_init = jax.ops.index_update(stocks_init,   # jax.ops.index_update(x, idx, y) <-> Pure equivalent of x[idx] = y
                            jax.ops.index[0],         # initialization of stock prices
                            initial_stocks)
    noise = jax.random.multivariate_normal(key, drift, cov, (numsteps+1,))
    sigma = jnp.diag(cov) ** 0.5
    def time_step(t, val):
        dx =  drift + noise[t,:] # no need to multiply by sigma here because noise generated by cov not corr
        dx2 = jnp.exp((drift - sigma ** 2. / 2.) + noise[t,:])
        val = jax.ops.index_update(val,
                            jax.ops.index[t],
                            val[t-1] * dx2)
        return val
    return jax.lax.fori_loop(1, numsteps+1, time_step, stocks_init)[1:] # jax.lax.fori_loop(lower, upper, body_fun, init_val)

def optionvalue(key, initial_stocks, numsteps, drift, cov, strike):
  return jnp.mean((jnp.maximum(batch_simple(keys, initial_stocks, numsteps, drift, cov)[:,-1,:]-strike,0))) # this is assuming 1 stock for testing price (didn't take avg)

def optionvalueavg(key, initial_stocks, numsteps, drift, cov, strike):
  return jnp.mean((jnp.maximum(jnp.mean(batch_simple(keys, initial_stocks, numsteps, drift, cov)[:,-1,:], axis=1)-strike,0))) # this is assuming 3 stocks in basket

In [3]:
# Peter's code

import jax
import jax.numpy as jnp
from jax import random
from jax import jit
import numpy as np
from torch.utils.dlpack import from_dlpack

numstocks = 3

rng = jax.random.PRNGKey(1)
rng, key = jax.random.split(rng)
#numsteps = 10
drift = jnp.array([0.0]*numstocks)

cov = jnp.identity(numstocks)*.25*.25
initial_stocks = jnp.array([100.]*numstocks)

K = 110.0

fast_simple = jax.jit(simple_process, static_argnums=2)
#fast_simple(key, initial_stocks, numsteps, drift, cov)

keys = jax.random.split(key, 1000000)
batch_simple = jax.vmap(fast_simple, in_axes=(0, None, None, None, None))

print(initial_stocks) #S = 100
print(K) #K = 110
print(cov) #sigma = 0.25
print(drift) #drift = 0

#################################################################################### values for checking
#S, K, r, sigma, T
# 100, 110, 0, 0.25, 1
# 1 stock price should be around 6.1904
# 3 stock price should be around 2.3767
# delta should be around (0.39888 / numstocks)
####################################################################################

# option price
# 1 stock
print(optionvalue(key, initial_stocks, 1, drift, cov, K)) # numsteps here = years = 1
# 3 stocks basket
print(optionvalueavg(key, initial_stocks, 1, drift, cov, K)) # numsteps here = years = 1

# delta test
gooptionvalue = jax.grad(optionvalue,argnums=1)
gooptionvalue(keys, initial_stocks, 1, drift, cov, K) # numsteps here = years = 1

[100. 100. 100.]
110.0
[[0.0625 0.     0.    ]
 [0.     0.0625 0.    ]
 [0.     0.     0.0625]]
[0. 0. 0.]
6.195753
2.3685586


DeviceArray([0.1331373 , 0.13304196, 0.13283278], dtype=float32)

In [4]:
def simple_process(key, initial_stocks, numsteps, drift, cov, T):
    stocks_init = jnp.zeros((numsteps + 1, initial_stocks.shape[0]))
    stocks_init = jax.ops.index_update(stocks_init,   # jax.ops.index_update(x, idx, y) <-> Pure equivalent of x[idx] = y
                            jax.ops.index[0],         # initialization of stock prices
                            initial_stocks)
    noise = jax.random.multivariate_normal(key, drift, cov, (numsteps+1,))
    sigma = jnp.diag(cov) ** 0.5
    dt = T / numsteps
    def time_step(t, val):
        #dx =  drift + noise[t,:] # no need to multiply by sigma here because noise generated by cov not corr
        dx2 = jnp.exp((drift - sigma ** 2. / 2.) * dt + jnp.sqrt(dt) * noise[t,:])
        val = jax.ops.index_update(val,
                            jax.ops.index[t],
                            val[t-1] * dx2)
        return val
    return jax.lax.fori_loop(1, numsteps+1, time_step, stocks_init)[1:] # jax.lax.fori_loop(lower, upper, body_fun, init_val)

def optionvalue(key, initial_stocks, numsteps, drift, cov, strike, T):
  return jnp.mean((jnp.maximum(batch_simple(keys, initial_stocks, numsteps, drift, cov, T)[:,-1,:]-strike,0))) # this is assuming 1 stock for testing price (didn't take avg)

def optionvalueavg(key, initial_stocks, numsteps, drift, cov, strike, T):
  return jnp.mean((jnp.maximum(jnp.mean(batch_simple(keys, initial_stocks, numsteps, drift, cov, T)[:,-1,:], axis=1)-strike,0))) # this is assuming 3 stocks in basket

numstocks = 3

rng = jax.random.PRNGKey(1)
rng, key = jax.random.split(rng)
numsteps = 50
drift = jnp.array([0.0]*numstocks)

cov = jnp.identity(numstocks)*.25*.25
initial_stocks = jnp.array([100.]*numstocks)

T = 1.0
K = 110.0

fast_simple = jax.jit(simple_process, static_argnums=2)
#fast_simple(key, initial_stocks, numsteps, drift, cov)

keys = jax.random.split(key, 1000000)
batch_simple = jax.vmap(fast_simple, in_axes=(0, None, None, None, None, None))

# print(initial_stocks) #S = 100
# print(K) #K = 110
# print(cov) #sigma = 0.25
# print(drift) #drift = 0

#################################################################################### values for checking
#S, K, r, sigma, T
# 100, 110, 0, 0.25, 1
# 1 stock price should be around 6.1904
# 3 stock price should be around 2.3767
# delta should be around (0.39888 / numstocks)
####################################################################################

# option price
# 1 stock
# print(optionvalue(key, initial_stocks, numsteps, drift, cov, K, T)) # numsteps here = 50, but T = year = 1
# 3 stocks basket
# print(optionvalueavg(key, initial_stocks, numsteps, drift, cov, K, T)) # numsteps here = 50, but T = year = 1

# delta test
gooptionvalue = jax.grad(optionvalue,argnums=1)
gooptionvalue(keys, initial_stocks, numsteps, drift, cov, K, T) # numsteps here = 50, but T = year = 1

DeviceArray([0.1331037 , 0.13305795, 0.13296409], dtype=float32)

# Random Test

In [55]:
numstocks = 2  # dimension of multivariate normal distribution
numsteps = 10000   # length of each random variable
numpath = 3  # number of split

drift = jnp.array([0.0]*numstocks)
cov = jnp.identity(numstocks)*.25*.25

rng = jax.random.PRNGKey(1)
rng, key = jax.random.split(rng)
keys = jax.random.split(key, numpath)
random_num = jax.random.multivariate_normal(keys[0], drift, cov, (numsteps+1,)).reshape((numstocks,(numsteps+1)))

indx = 0
for i in range(1,numpath):
  new_random_num = jax.random.multivariate_normal(keys[i], drift, cov, (numsteps+1,)).reshape((numstocks,(numsteps+1)))
  # random_num = jax.ops.index_update(random_num,
  #                 jax.ops.index[indx],
  #                           new_random_num)
  random_num = jax.numpy.append(random_num, new_random_num, axis=0)
  indx += 1

correlation

In [53]:
jnp.corrcoef(random_num)

DeviceArray([[ 9.99999881e-01, -8.33061989e-03, -1.06057944e-02,
               1.61927883e-02,  1.56237725e-02,  1.96916936e-03,
              -2.40133610e-02, -1.15213245e-02,  1.10734859e-02,
              -1.04135582e-02, -1.87602860e-03, -4.75532562e-03,
               5.07578393e-03, -1.16232818e-03,  7.29561958e-04],
             [-8.33061896e-03,  1.00000000e+00,  1.92225017e-02,
              -1.33640673e-02, -2.17897277e-02,  9.73478146e-03,
              -1.12325754e-02,  2.85502803e-02,  1.89116877e-03,
               2.40466073e-02, -9.29636043e-03, -3.78370751e-03,
              -3.34145576e-02,  1.25947958e-02,  1.75473443e-03],
             [-1.06057944e-02,  1.92225035e-02,  1.00000000e+00,
              -1.63686695e-03,  9.02404543e-03,  4.43008449e-03,
              -2.36400170e-03, -7.99175701e-04,  3.52322534e-02,
              -5.77173801e-03, -1.33366548e-02,  1.53499357e-02,
              -2.03444790e-02, -5.47258276e-03,  1.18152713e-02],
             [ 1.61927

average

In [59]:
for i in random_num:
  print(jnp.average(i)) 

0.0009462589
-0.0002223529
-8.752425e-05
0.0025754324
-0.0027612
0.0023144407
