<a href="https://colab.research.google.com/github/xinyanz-erin/Applied-Finance-Project/blob/Judy/lstsq_Problem_Update.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import jax
import jax.numpy as jnp
import numpy as np
from numpy.linalg import inv

## Test1

In [3]:
def ls1_m(in_put):
    return in_put/in_put
def ls2_m(in_put):
    return in_put
def ls3_m(in_put):
    return in_put**2

In [4]:
AA_X = np.array([1.0880001e+02,1.0010000e+02,1.1020000e+02,1.2010000e+02,9.8199997e+01])
Y_X = np.array([23.521464,0.000000,1.694343,30.797171,0.000000])
AA_Pui_X = np.array([[np.sum(ls1_m(AA_X) **2),np.sum(ls1_m(AA_X) * ls2_m(AA_X)),np.sum(ls1_m(AA_X) * ls3_m(AA_X))],
                          [np.sum(ls2_m(AA_X) * ls1_m(AA_X)),np.sum(ls2_m(AA_X) ** 2), np.sum(ls2_m(AA_X) * ls3_m(AA_X))],
                          [np.sum(ls3_m(AA_X) * ls1_m(AA_X)) , np.sum(ls3_m(AA_X) * ls2_m(AA_X)),np.sum(ls3_m(AA_X) ** 2)]])
A_inv_X = inv(AA_Pui_X)
b_X = np.array([[np.sum(Y_X * ls1_m(AA_X))],[np.sum(Y_X * ls2_m(AA_X))],[np.sum(Y_X * ls3_m(AA_X))]])
a_s_X = np.dot(A_inv_X,b_X)
a_s_X

array([[ 1.52887760e+02],
       [-3.97191757e+00],
       [ 2.45585261e-02]])

In [5]:
AA_Pui = np.array([[1.0000000e+00, 1.0880001e+02, 1.1837442e+04],
          [1.0000000e+00, 1.0010000e+02, 1.0020010e+04],
          [1.0000000e+00, 1.1020000e+02, 1.2144039e+04],
           [1.0000000e+00, 1.2010000e+02, 1.4424010e+04],
           [1.0000000e+00, 9.8199997e+01, 9.6432393e+03]])

In [6]:
B = np.array([23.521464,0.000000,1.694343,30.797171,0.000000])

In [7]:
np.linalg.lstsq(AA_Pui,B,rcond = None)[0]

array([ 1.52894188e+02, -3.97203636e+00,  2.45590726e-02])

In [8]:
AA_Pui_jax = jnp.array([[1.0000000e+00, 1.0880001e+02, 1.1837442e+04],
          [1.0000000e+00, 1.0010000e+02, 1.0020010e+04],
          [1.0000000e+00, 1.1020000e+02, 1.2144039e+04],
           [1.0000000e+00, 1.2010000e+02, 1.4424010e+04],
           [1.0000000e+00, 9.8199997e+01, 9.6432393e+03]])

In [9]:
B_jax = jnp.array([23.521464,0.000000,1.694343,30.797171,0.000000])

In [21]:
jax.numpy.linalg.lstsq(AA_Pui_jax, B_jax,rcond = -1)[0]

DeviceArray([ 1.5286615e+02, -3.9715176e+00,  2.4556689e-02], dtype=float32)

In [22]:
jax.numpy.linalg.lstsq(AA_Pui_jax, B_jax)[0]

DeviceArray([-0.02124668, -1.1520692 ,  0.01162804], dtype=float32)

## Test2

In [23]:
Y = np.array([0,4.1759,6.7863,6.9345])
X = np.array([92.8,96.34,89.37,86.12])
X_2 = np.c_[X**2,X,np.ones_like(X)]

In [24]:
X_2

array([[8.6118400e+03, 9.2800000e+01, 1.0000000e+00],
       [9.2813956e+03, 9.6340000e+01, 1.0000000e+00],
       [7.9869969e+03, 8.9370000e+01, 1.0000000e+00],
       [7.4166544e+03, 8.6120000e+01, 1.0000000e+00]])

In [25]:
X_2_test = np.c_[np.ones_like(X),X,X**2]
X_2_test

array([[1.0000000e+00, 9.2800000e+01, 8.6118400e+03],
       [1.0000000e+00, 9.6340000e+01, 9.2813956e+03],
       [1.0000000e+00, 8.9370000e+01, 7.9869969e+03],
       [1.0000000e+00, 8.6120000e+01, 7.4166544e+03]])

In [ ]:
## Using Simple Polynomials function

In [ ]:
def ls1_m(in_put):
    return in_put/in_put
def ls2_m(in_put):
    return in_put
def ls3_m(in_put):
    return in_put**2 

In [26]:
A = np.array([[np.sum(ls1_m(X) **2),np.sum(ls1_m(X) * ls2_m(X)),np.sum(ls1_m(X) * ls3_m(X))],
                          [np.sum(ls2_m(X) * ls1_m(X)),np.sum(ls2_m(X) ** 2), np.sum(ls2_m(X) * ls3_m(X))],
                          [np.sum(ls3_m(X) * ls1_m(X)) , np.sum(ls3_m(X) * ls2_m(X)),np.sum(ls3_m(X) ** 2)]])
A_inv = inv(A)
b = np.array([[np.sum(Y * ls1_m(X))],[np.sum(Y* ls2_m(X))],[np.sum(Y * ls3_m(X))]])
a_s = np.dot(A_inv,b)
a_s

array([[ 8.83369606e+02],
       [-1.88603524e+01],
       [ 1.00954440e-01]])

In [ ]:
## Using statsmodel

In [27]:
import statsmodels.api as sm
mod = sm.OLS(Y, X_2).fit()
mod.params[::-1]

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


array([ 8.83369607e+02, -1.88603524e+01,  1.00954440e-01])

In [ ]:
## Using numpy linalg.lstsq

In [28]:
np.linalg.lstsq(X_2,Y,rcond = None)[0][::-1]

array([ 8.83369607e+02, -1.88603524e+01,  1.00954440e-01])

In [ ]:
## Using sklearn(Not working)

In [29]:
from sklearn.linear_model import LinearRegression
model = LinearRegression().fit(X_2,Y)
model.coef_[::-1]

array([  0.        , -18.86035239,   0.10095444])

In [ ]:
## Using Jax linalg lstsq(Not working)

In [30]:
Y_jax = jnp.array([0,4.1759,6.7863,6.9345])
X_jax = jnp.array([92.8,96.34,89.37,86.12])
X_2_jax = jnp.c_[X_jax**2,X_jax,np.ones_like(X)]

In [32]:
jnp.linalg.lstsq(X_2,Y,rcond = -1)[0][::-1]

DeviceArray([ 8.8335382e+02, -1.8859987e+01,  1.0095232e-01], dtype=float32)

In [ ]:
## Using "Original" Method (Not Working since not knowing the epsilon assumption)
sig = jnp.diag(jnp.array([1]*X_2_jax.shape[0]))
beta_temp = jnp.dot(jnp.dot(jnp.dot(np.linalg.inv(jnp.dot(jnp.dot(X_2_jax.transpose(), np.linalg.inv(sig)), X_2_jax)), X_2_jax.transpose()), np.linalg.inv(sig)), Y_jax)
print(beta_temp[::-1])

[ 9.66557617e+02 -2.06943016e+01  1.10961854e-01]


In [ ]:
beta_temp = jnp.dot(jnp.dot(jnp.linalg.inv(jnp.dot(X_2_jax.transpose(), X_2_jax)),X_2_jax.transpose()), Y_jax)

In [ ]:
beta_temp[::-1]

DeviceArray([ 9.2939325e+02, -1.9877731e+01,  1.0651436e-01], dtype=float32)

In [ ]:
mod.params[::-1]

array([ 8.83369607e+02, -1.88603524e+01,  1.00954440e-01])

## Jax Problem

In [ ]:
A = np.array([[np.sum(ls1_m(X) **2),np.sum(ls1_m(X) * ls2_m(X)),np.sum(ls1_m(X) * ls3_m(X))],
                          [np.sum(ls2_m(X) * ls1_m(X)),np.sum(ls2_m(X) ** 2), np.sum(ls2_m(X) * ls3_m(X))],
                          [np.sum(ls3_m(X) * ls1_m(X)) , np.sum(ls3_m(X) * ls2_m(X)),np.sum(ls3_m(X) ** 2)]])
print(A)

# A_inv = inv(A)
# b = np.array([[np.sum(Y * ls1_m(X))],[np.sum(Y* ls2_m(X))],[np.sum(Y * ls3_m(X))]])
# a_s = np.dot(A_inv,b)
# a_s

[[4.00000000e+00 3.64630000e+02 3.32968869e+04]
 [3.64630000e+02 3.32968869e+04 3.04586859e+06]
 [3.32968869e+04 3.04586859e+06 2.79106974e+08]]


In [ ]:
A_jax = jnp.array([[jnp.sum(ls1_m(X_jax) **2),jnp.sum(ls1_m(X_jax) * ls2_m(X_jax)),jnp.sum(ls1_m(X_jax) * ls3_m(X_jax))],
                          [jnp.sum(ls2_m(X_jax) * ls1_m(X_jax)),jnp.sum(ls2_m(X_jax) ** 2), jnp.sum(ls2_m(X_jax) * ls3_m(X_jax))],
                          [jnp.sum(ls3_m(X_jax) * ls1_m(X_jax)) , jnp.sum(ls3_m(X_jax) * ls2_m(X_jax)),jnp.sum(ls3_m(X_jax) ** 2)]])
print(A_jax)

[[4.0000000e+00 3.6462997e+02 3.3296887e+04]
 [3.6462997e+02 3.3296887e+04 3.0458688e+06]
 [3.3296887e+04 3.0458688e+06 2.7910701e+08]]


In [ ]:
np.linalg.inv(A)  # np.inv and jnp.inv diff

array([[ 1.28921818e+05, -2.82923072e+03,  1.54950259e+01],
       [-2.82923072e+03,  6.21057370e+01, -3.40232768e-01],
       [ 1.54950259e+01, -3.40232768e-01,  1.86440765e-03]])

In [ ]:
jnp.linalg.inv(jnp.array(A))

DeviceArray([[ 1.24507492e+05, -2.73230249e+03,  1.49638767e+01],
             [-2.73228784e+03,  5.99771004e+01, -3.28568220e-01],
             [ 1.49637165e+01, -3.28566462e-01,  1.80047844e-03]],            dtype=float32)

In [ ]:
# Right Coefs
A_inv = inv(A)
b = np.array([[np.sum(Y * ls1_m(X))],[np.sum(Y* ls2_m(X))],[np.sum(Y * ls3_m(X))]])
a_s = np.dot(A_inv,b)
a_s

array([[ 8.83064194e+02],
       [-1.88536480e+01],
       [ 1.00917711e-01]])

In [ ]:
# Wrong Coefs
A_inv_jax = jnp.linalg.inv(A_jax)
b_jax = jnp.array([[jnp.sum(Y_jax * ls1_m(X_jax))],[jnp.sum(Y_jax* ls2_m(X_jax))],[jnp.sum(Y_jax * ls3_m(X_jax))]])
a_s_jax = jnp.dot(A_inv_jax,b_jax)
a_s_jax

DeviceArray([[ 8.0387500e+02],
             [-1.7121094e+01],
             [ 9.1445923e-02]], dtype=float32)