<a href="https://colab.research.google.com/github/xinyanz-erin/Applied-Finance-Project/blob/Judy/lstsq_Problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import jax
import jax.numpy as jnp
import numpy as np
from numpy.linalg import inv

## Test1

In [2]:
AA_Pui = np.array([[1.0000000e+00, 1.0880001e+02, 1.1837442e+04],
          [1.0000000e+00, 1.0010000e+02, 1.0020010e+04],
          [1.0000000e+00, 1.1020000e+02, 1.2144039e+04],
           [1.0000000e+00, 1.2010000e+02, 1.4424010e+04],
           [1.0000000e+00, 9.8199997e+01, 9.6432393e+03]])

In [11]:
B = np.array([23.521464,0.000000,1.694343,30.797171,0.000000])

In [13]:
np.linalg.lstsq(AA_Pui,B,rcond = None)[0]

array([ 1.52894188e+02, -3.97203636e+00,  2.45590726e-02])

In [5]:
AA_Pui_jax = jnp.array([[1.0000000e+00, 1.0880001e+02, 1.1837442e+04],
          [1.0000000e+00, 1.0010000e+02, 1.0020010e+04],
          [1.0000000e+00, 1.1020000e+02, 1.2144039e+04],
           [1.0000000e+00, 1.2010000e+02, 1.4424010e+04],
           [1.0000000e+00, 9.8199997e+01, 9.6432393e+03]])

In [8]:
B_jax = jnp.array([23.521464,0.000000,1.694343,30.797171,0.000000])

In [10]:
jax.numpy.linalg.lstsq(AA_Pui_jax, B_jax)[0]

DeviceArray([-0.02124668, -1.1520692 ,  0.01162804], dtype=float32)

## Test2

In [7]:
def ls1_m(in_put):
    return in_put/in_put
def ls2_m(in_put):
    return in_put
def ls3_m(in_put):
    return in_put**2 

In [2]:
Y = np.array([0,4.1759,6.7863,6.9345])
X = np.array([92.8,96.34,89.37,86.12])
X_2 = np.c_[X**2,X,np.ones_like(X)]

In [10]:
A = np.array([[np.sum(ls1_m(X) **2),np.sum(ls1_m(X) * ls2_m(X)),np.sum(ls1_m(X) * ls3_m(X))],
                          [np.sum(ls2_m(X) * ls1_m(X)),np.sum(ls2_m(X) ** 2), np.sum(ls2_m(X) * ls3_m(X))],
                          [np.sum(ls3_m(X) * ls1_m(X)) , np.sum(ls3_m(X) * ls2_m(X)),np.sum(ls3_m(X) ** 2)]])
A_inv = inv(A)
b = np.array([[np.sum(Y * ls1_m(X))],[np.sum(Y* ls2_m(X))],[np.sum(Y * ls3_m(X))]])
a_s = np.dot(A_inv,b)
a_s

array([[ 8.83369606e+02],
       [-1.88603524e+01],
       [ 1.00954440e-01]])

In [4]:
np.linalg.lstsq(X_2,Y,rcond = None)[0][::-1]

array([ 8.83369607e+02, -1.88603524e+01,  1.00954440e-01])

In [5]:
Y_jax = jnp.array([0,4.1759,6.7863,6.9345])
X_jax = jnp.array([92.8,96.34,89.37,86.12])
X_2_jax = jnp.c_[X_jax**2,X_jax,np.ones_like(X)]

In [6]:
jnp.linalg.lstsq(X_2,Y,rcond = None)[0][::-1]

DeviceArray([ 0.0115269,  0.5252273, -0.0052158], dtype=float32)