<a href="https://colab.research.google.com/github/xinyanz-erin/Applied-Finance-Project/blob/Erin/PyTorch_tutorials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import torch
import torch.nn as nn

In [2]:
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


In [3]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

print(x)
print(y)

tensor([[0.2271, 0.8029],
        [0.5635, 0.3506]])
tensor([[0.2330, 0.3312],
        [0.6936, 0.7319]])


In [4]:
z = x + y
print(z)

tensor([[0.4601, 1.1341],
        [1.2571, 1.0825]])


In [5]:
z = torch.add(x, y)
print(z)

tensor([[0.4601, 1.1341],
        [1.2571, 1.0825]])


In [6]:
y.add_(x)
print(y)

tensor([[0.4601, 1.1341],
        [1.2571, 1.0825]])


In [7]:
z = torch.sub(x, y)
print(z)

tensor([[-0.2330, -0.3312],
        [-0.6936, -0.7319]])


In [8]:
z = torch.mul(x, y)
print(z)

tensor([[0.1045, 0.9105],
        [0.7084, 0.3795]])


In [9]:
y .mul_(x)

tensor([[0.1045, 0.9105],
        [0.7084, 0.3795]])

In [10]:
z = x / y
z = torch.div(x, y)

In [11]:
z

tensor([[2.1732, 0.8818],
        [0.7955, 0.9238]])

In [12]:
x = torch.rand(5, 3)
print(x[:, 0])

tensor([2.1300e-01, 2.6226e-01, 7.3961e-01, 4.7028e-04, 3.5263e-01])


In [13]:
print(x)

tensor([[2.1300e-01, 6.3804e-01, 3.6742e-01],
        [2.6226e-01, 1.1899e-02, 2.3420e-01],
        [7.3961e-01, 1.8617e-01, 1.2943e-01],
        [4.7028e-04, 8.2000e-01, 5.1187e-01],
        [3.5263e-01, 4.6207e-01, 4.6281e-03]])


In [14]:
print(x[1, 1])

tensor(0.0119)


In [15]:
print(x[1, 1].item())

0.011899232864379883


In [16]:
x = torch.rand(4, 4)
print(x)

tensor([[0.6791, 0.9708, 0.6766, 0.5781],
        [0.0217, 0.8539, 0.5545, 0.6247],
        [0.4823, 0.5198, 0.4475, 0.4811],
        [0.6973, 0.0847, 0.0341, 0.1251]])


In [17]:
y = x.view(16)
print(y)

tensor([0.6791, 0.9708, 0.6766, 0.5781, 0.0217, 0.8539, 0.5545, 0.6247, 0.4823,
        0.5198, 0.4475, 0.4811, 0.6973, 0.0847, 0.0341, 0.1251])


In [18]:
y = x.view(-1, 8)
print(y.size())
print(y)

torch.Size([2, 8])
tensor([[0.6791, 0.9708, 0.6766, 0.5781, 0.0217, 0.8539, 0.5545, 0.6247],
        [0.4823, 0.5198, 0.4475, 0.4811, 0.6973, 0.0847, 0.0341, 0.1251]])


In [19]:
import numpy as np

In [20]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [22]:
print(type(b))

<class 'numpy.ndarray'>


In [23]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [24]:
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [25]:
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [26]:
if torch.cuda.is_available():
  device = torch.device('cude')
  x = torch.ones(5, device = device)
  y = torch.ones(5)
  y = y.to(device)
  z = x + y
  z = z.to('cpu')

In [27]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


In [28]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([ 0.3688, -0.5061, -0.2591], requires_grad=True)


In [29]:
y = x + 2
print(y)

tensor([2.3688, 1.4939, 1.7409], grad_fn=<AddBackward0>)


In [30]:
z = y * y * 2
print(z)

tensor([11.2226,  4.4633,  6.0615], grad_fn=<MulBackward0>)


In [31]:
# z = z.mean()
# print(z)

In [32]:
v = torch.tensor([0.1, 1.0, 0.001], dtype = torch.float32)
z.backward(v) #dz/dx
print(x.grad)

tensor([0.9475, 5.9755, 0.0070])


In [33]:
# x.requires_grad_(False)
# x.detach()
# with torch.no_grad():
#   y = x + 2
#   print(y)

In [34]:
weights = torch.ones(4, requires_grad=True)

In [35]:
for epoch in range(2):
  model_output = (weights * 3).sum()

  model_output.backward()

  print(weights.grad)

  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [36]:
# opimizer = torch.optim.SGD(weights, lr = 0.01)
# optimizer.step()
# optimizer.zero_grad_()

In [37]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0, requires_grad=True)

# forward pass and compute the loss
y_hat = w * x
loss = (y_hat - y) ** 2

print(loss)

# backward pass
loss.backward()
print(w.grad)

## update weights
## next forward and backwards

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


In [38]:
import numpy as np

In [39]:
X = np.array([1, 2, 3, 4], dtype=np.float32)
Y = np.array([2, 4, 6, 8], dtype=np.float32)

w = 0.0

In [40]:
def forward(x):
  return w * x

def loss(y, y_pred):
  return((y_pred - y) ** 2).mean()

# gradient
# MSE = 1/N * (w * x - y) ** 2
# dJ/dw = 1/N * 2x * (w*x - y)

def gradient(x, y, y_pre):
  return np.dot(2*x, y_pre - y).mean()

print(f'Prediction before training: f(5) = {forward(5): .3f}')

# Training
learning_rate = 0.01
n_iters = 19

for epoch in range(n_iters):
  y_pred = forward(X)
  l = loss(Y, y_pred)
  dw = gradient(X, Y, y_pred)

  w -= learning_rate * dw

  if epoch % 1 == 0:
    print(f'epoch {epoch + 1}: w = {w: .3f}, loss = {l: .8f}')

print(f'Prediction after training: f(5) = {forward(5):.3f}')

Prediction before training: f(5) =  0.000
epoch 1: w =  1.200, loss =  30.00000000
epoch 2: w =  1.680, loss =  4.79999924
epoch 3: w =  1.872, loss =  0.76800019
epoch 4: w =  1.949, loss =  0.12288000
epoch 5: w =  1.980, loss =  0.01966083
epoch 6: w =  1.992, loss =  0.00314574
epoch 7: w =  1.997, loss =  0.00050331
epoch 8: w =  1.999, loss =  0.00008053
epoch 9: w =  1.999, loss =  0.00001288
epoch 10: w =  2.000, loss =  0.00000206
epoch 11: w =  2.000, loss =  0.00000033
epoch 12: w =  2.000, loss =  0.00000005
epoch 13: w =  2.000, loss =  0.00000001
epoch 14: w =  2.000, loss =  0.00000000
epoch 15: w =  2.000, loss =  0.00000000
epoch 16: w =  2.000, loss =  0.00000000
epoch 17: w =  2.000, loss =  0.00000000
epoch 18: w =  2.000, loss =  0.00000000
epoch 19: w =  2.000, loss =  0.00000000
Prediction after training: f(5) = 10.000


In [41]:
X = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
Y = torch.tensor([2, 4, 6, 8], dtype=torch.float32)

w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

def forward(x):
  return w * x

def loss(y, y_pred):
  return((y_pred - y) ** 2).mean()

print(f'Prediction before training: f(5) = {forward(5): .3f}')

# Training
learning_rate = 0.01
n_iters = 100

for epoch in range(n_iters):
  y_pred = forward(X)
  l = loss(Y, y_pred)
  l.backward() # dl/dw

  with torch.no_grad():
    w -= learning_rate * w.grad

  # zero gradients
  w.grad.zero_()

  if epoch % 10 == 0:
    print(f'epoch {epoch + 1}: w = {w: .3f}, loss = {l: .8f}')

print(f'Prediction after training: f(5) = {forward(5):.3f}')

Prediction before training: f(5) =  0.000
epoch 1: w =  0.300, loss =  30.00000000
epoch 11: w =  1.665, loss =  1.16278565
epoch 21: w =  1.934, loss =  0.04506890
epoch 31: w =  1.987, loss =  0.00174685
epoch 41: w =  1.997, loss =  0.00006770
epoch 51: w =  1.999, loss =  0.00000262
epoch 61: w =  2.000, loss =  0.00000010
epoch 71: w =  2.000, loss =  0.00000000
epoch 81: w =  2.000, loss =  0.00000000
epoch 91: w =  2.000, loss =  0.00000000
Prediction after training: f(5) = 10.000


In [52]:
X = torch.tensor([1, 2, 3, 4], dtype = torch.float32)
Y = torch.tensor([4, 8, 12, 16], dtype = torch.float32)

w = torch.tensor(0.0, dtype = torch.float32, requires_grad=True)

def forward(x):
  return w * x

learning_rate = 0.01
n_iters = 100

loss = nn.MSELoss()
optimizer = torch.optim.SGD([w], lr = learning_rate)

In [53]:
for epoch in range(n_iters):
  y_pred = forward(X)

  l = loss(Y, y_pred)

  l.backward()

  optimizer.step() #update weights

  optimizer.zero_grad()

  if epoch % 10 == 0:
    print(f'epoch {epoch + 1}: w = {w: .3f}, loss = {l: .8f}')

print(f'Prediction after training: f(5) = {forward(5):.3f}')

epoch 1: w =  0.600, loss =  120.00000000
epoch 11: w =  3.331, loss =  4.65114260
epoch 21: w =  3.868, loss =  0.18027559
epoch 31: w =  3.974, loss =  0.00698742
epoch 41: w =  3.995, loss =  0.00027082
epoch 51: w =  3.999, loss =  0.00001050
epoch 61: w =  4.000, loss =  0.00000041
epoch 71: w =  4.000, loss =  0.00000002
epoch 81: w =  4.000, loss =  0.00000000
epoch 91: w =  4.000, loss =  0.00000000
Prediction after training: f(5) = 20.000
