<a href="https://colab.research.google.com/github/xinyanz-erin/Applied-Finance-Project/blob/Erin/PyTorch_tutorials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports

In [1]:
import torch
import torch.nn as nn
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt

# 1. Installation

# 2. Tensor Basics

In [2]:
x = torch.empty(2, 3, 2, 3)
print(x)

tensor([[[[6.4880e-35, 3.0805e-41, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]]],


        [[[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]]]])


In [3]:
x = torch.rand(2, 2) # random numbers
print(x)

tensor([[0.9546, 0.0911],
        [0.5403, 0.5306]])


In [4]:
x = torch.zeros(2, 2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [5]:
x = torch.ones(2, 2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [6]:
print(x.dtype)

torch.float32


In [7]:
x = torch.ones(2, 2, dtype = torch.int)
print(x)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)


In [8]:
x = torch.ones(2, 2, dtype = torch.float16)
print(x)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)


In [9]:
print(x.size())

torch.Size([2, 2])


In [10]:
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


In [11]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)
z = x + y
print(z)

tensor([[0.3362, 0.0880],
        [0.4182, 0.0709]])
tensor([[0.0123, 0.5144],
        [0.7061, 0.5814]])
tensor([[0.3485, 0.6024],
        [1.1243, 0.6523]])


In [12]:
z = torch.add(x, y)
print(z)

tensor([[0.3485, 0.6024],
        [1.1243, 0.6523]])


In [13]:
y.add_(x)
print(y)

tensor([[0.3485, 0.6024],
        [1.1243, 0.6523]])


In [14]:
z = x - y
z = torch.sub(x, y)
print(z)

tensor([[-0.0123, -0.5144],
        [-0.7061, -0.5814]])


In [15]:
z = x * y
z = torch.mul(x, y)
print(z)

tensor([[0.1172, 0.0530],
        [0.4702, 0.0463]])


In [16]:
y.mul_(x)
print(y)

tensor([[0.1172, 0.0530],
        [0.4702, 0.0463]])


In [17]:
z = x / y
z = torch.div(x, y)
print(z)

tensor([[2.8693, 1.6599],
        [0.8894, 1.5330]])


In [18]:
x = torch.rand(5, 3)
print(x)
print(x[1, 1])
print(x[1, 1].item())
print(x[:,2])

tensor([[0.3851, 0.4006, 0.9133],
        [0.2770, 0.3402, 0.1816],
        [0.7197, 0.4773, 0.7210],
        [0.9433, 0.9885, 0.6366],
        [0.5377, 0.3686, 0.0881]])
tensor(0.3402)
0.3401545286178589
tensor([0.9133, 0.1816, 0.7210, 0.6366, 0.0881])


In [19]:
x = torch.rand(4, 4)
print(x)
y = x.view(16)
print(y)
y = x.view(-1, 8)
print(y)

tensor([[0.1487, 0.0156, 0.0161, 0.5940],
        [0.9050, 0.8816, 0.3242, 0.7266],
        [0.7466, 0.7181, 0.4525, 0.4894],
        [0.2308, 0.2017, 0.0548, 0.5653]])
tensor([0.1487, 0.0156, 0.0161, 0.5940, 0.9050, 0.8816, 0.3242, 0.7266, 0.7466,
        0.7181, 0.4525, 0.4894, 0.2308, 0.2017, 0.0548, 0.5653])
tensor([[0.1487, 0.0156, 0.0161, 0.5940, 0.9050, 0.8816, 0.3242, 0.7266],
        [0.7466, 0.7181, 0.4525, 0.4894, 0.2308, 0.2017, 0.0548, 0.5653]])


In [20]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [21]:
print(type(b))

<class 'numpy.ndarray'>


In [22]:
a.add_(1)
print(a)

tensor([2., 2., 2., 2., 2.])


In [23]:
print(b)

[2. 2. 2. 2. 2.]


In [24]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [25]:
a += 1
print(a)

[2. 2. 2. 2. 2.]


In [26]:
print(b)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [27]:
if torch.cuda.is_available():
  device = torch.device('cuda')
  x = torch.ones(5, device = device)
  y = torch.ones(5)
  y = y.to(device)
  z = x + y # perform on gpu
  # z.numpy() # return error if on gpu since numpy can only handle cpu
  z = z.to('cpu') # on cpu again

In [28]:
torch.cuda.is_available()

False

In [29]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


# 3. Gradient Calculation With Autograd

In [30]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([0.1880, 0.5288, 1.9651], requires_grad=True)


In [31]:
y = x + 2
print(y)

tensor([2.1880, 2.5288, 3.9651], grad_fn=<AddBackward0>)


In [32]:
z = y*y*2
z = z.mean()
print(z)

tensor(17.9363, grad_fn=<MeanBackward0>)


In [33]:
z.backward() # dz/dx
print(x.grad)

tensor([2.9173, 3.3718, 5.2869])


In [34]:
z = y*y*2
v = torch.tensor([0.1, 1.0, 0.01], dtype = torch.float32)
z.backward(v) # dz/dx
print(x.grad)

tensor([ 3.7924, 13.4871,  5.4455])


In [35]:
x = torch.randn(3, requires_grad=True)
print(x)
x.requires_grad_(False)
print(x)

tensor([-0.6340,  1.4689, -0.0076], requires_grad=True)
tensor([-0.6340,  1.4689, -0.0076])


In [36]:
y = x.detach()
print(y)

tensor([-0.6340,  1.4689, -0.0076])


In [37]:
with torch.no_grad():
  y = x + 2
  print(y)

tensor([1.3660, 3.4689, 1.9924])


In [41]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
  
  model_output = (weights * 3).sum()

  model_output.backward()

  print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [45]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
  
  model_output = (weights * 3).sum()

  model_output.backward()

  print(weights.grad)

  weights.grad.zero_() # empty the gradient 

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


# 4. Backpropagation